enableRedstone: true
messagePriority: 3
debugPriority: 1
operatorPermissions: true
showPlacements: true
mysql:
  enabled: false
  host: 'localhost'
  port: 3306
  database: 'minecraft'
  table: 'homeTable'
  username: 'root'
  password: 'password'